#  "postgres://username:password@localhost:5432/database_name"
# username:password@protocol(address)/dbname?param=value
datasource:
  ds1:
    driver: sqlite3
    user: abc
    password: 123
    url: file:test3.db?cache=shared&mode=memory
    scripts:
      - sqlite3-schema.sql
      - sqlite3-init.sql

