#  "postgres://username:password@localhost:5432/database_name"
# username:password@protocol(address)/dbname?param=value
datasource:
  ds1:
    driver: postgresql
    user: dd
    password: dd
    host: locaalhost
    port: 12345
    db: abc
  ds2:
    driver: mysql
    user: dd
    password: dd
    host: locaalhost
    port: 12345
    db: abc


